version: "3.9"

services:
  eventrouter:
    container_name: eventrouter
    command: "./bin/start_event_router"
    ports:
      - "8080:8080"
    env_file:
      - .envrc
    environment: []
    build:
      dockerfile: Dockerfile
      context: .    
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: event_store
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/