version: "3.9"

services:
  eventrouter:
    container_name: eventrouter
    command: "./bin/start_event_router"
    ports:
      - "8080:8080"
    env_file:
      - .envrc
    environment: []
    build:
      dockerfile: Dockerfile
      context: .    
    restart: always

  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - db-data:/data

volumes:
  db-data: