version: "3.9"

services:
  eventrouter:
    container_name: event_router_server
    command: "./bin/start_event_router"
    ports:
      - "8080:8080"
    env_file:
      - .envrc
    environment: []
    build:
      dockerfile: Dockerfile
      context: .    
    restart: always