version: "3.9"

services:
  eventrouter_it:
    container_name: eventrouter_it
    command: "./bin/start_event_router"
    env_file:
      - .envrc
    environment: 
      DB_NAME: "codenames"
      DB_URI: "redis_it:6379"
      WS_HOST: "eventrouter_it"
      WS_PORT: "8080"
    build:
      dockerfile: Dockerfile
      context: .    
    restart: always
    depends_on:
      - redis_it
    networks:
      - tests

  redis_it:
    image: redis:7.0.4-alpine
    restart: always
    networks:
      - tests

  event_router_integration_test:
    container_name: event_router_integration_test
    command: "go test -timeout 10s -v -cover ./..."
    env_file:
      - .envrc
    environment:
      DB_NAME: "codenames"
      DB_URI: "redis_it:6379"
      WS_HOST: "eventrouter_it"
      WS_PORT: "8080"
    build:
      dockerfile: Dockerfile
      context: .    
    restart: "no"
    depends_on:
      - redis_it
      - eventrouter_it
    networks:
      - tests

  init-redis:
    depends_on:
      - redis_it
    image: redis:7.0.4-alpine
    restart: "no"
    volumes: 
      - ./internal/database/init_test/:/init_test/:ro
    command: sh -c "cat /init_test/test_data.txt | redis-cli -h redis_it -p 6379 --pipe"
    networks:
      - tests

  redis-insight-it:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - "8002:8001"
    networks:
      - tests


networks:
  tests: